# Generated by Django 6.0.2 on 2026-03-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_level_user_alter_types_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
