# Generated by Django 6.0.1 on 2026-02-10 19:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_id', models.CharField(max_length=100, unique=True)),
                ('claim_type', models.CharField(choices=[('organic', 'Organic'), ('locally_sourced', 'Locally sourced'), ('fairtrade', 'Fairtrade'), ('recycled', 'Recycled materials'), ('other', 'Other')], default='other', max_length=50)),
                ('statement', models.CharField(max_length=300)),
                ('missing_evidence', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_id', models.CharField(max_length=100, unique=True)),
                ('scope', models.CharField(choices=[('product', 'Product'), ('stage', 'Stage')], max_length=20)),
                ('evidence_type', models.CharField(max_length=50)),
                ('issuer', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingredient_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=100, unique=True)),
                ('org_name', models.CharField(max_length=160)),
                ('role', models.CharField(choices=[('farm', 'Farm'), ('factory', 'Factory'), ('refinery', 'Refinery'), ('retailer', 'Retailer'), ('assembler', 'Assembler'), ('distributor', 'Distributor'), ('other', 'Other')], default='other', max_length=20)),
                ('country', models.CharField(max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('qr_token', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_evidence_links', to='passport.claim')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_evidence_links', to='passport.evidence')),
            ],
        ),
        migrations.AddField(
            model_name='evidence',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='passport.product'),
        ),
        migrations.AddField(
            model_name='claim',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='passport.product'),
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proportion', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('origin_country', models.CharField(max_length=2)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='passport.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='passport.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_id', models.CharField(max_length=100, unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('stage_name', models.CharField(max_length=150)),
                ('value_share', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages_out', to='passport.node')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='passport.product')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages_in', to='passport.node')),
            ],
        ),
        migrations.AddField(
            model_name='evidence',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='passport.stage'),
        ),
        migrations.AddField(
            model_name='claim',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='passport.stage'),
        ),
    ]
