# Generated by Django 6.0.1 on 2026-02-18 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_productscan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='country',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='origin_country',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
