# Generated by Django 6.0.2 on 2026-03-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0003_alter_node_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='claim',
            name='evidence',
            field=models.ManyToManyField(blank=True, through='passport.ClaimEvidence', to='passport.evidence'),
        ),
    ]
