# Generated by Django 6.0.2 on 2026-03-18 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="example",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="learning_outcome",
            field=models.TextField(blank=True),
        ),
    ]
