<<<<<<< HEAD
# Generated by Django 6.0.1 on 2026-03-09 13:20
=======
# Generated by Django 6.0.2 on 2026-02-19 11:42
>>>>>>> 56aa0209c9952fcc0e8edb1d756b8cb3affb581a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='example',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='learning_outcome',
            field=models.TextField(blank=True),
        ),
    ]
